#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for backend/executor/model
#
# IDENTIFICATION
#    $PostgreSQL: pgsql/src/backend/model/Makefile$
#
#-------------------------------------------------------------------------

subdir = src/backend/model
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS = model.o bmodel.o stl.o ts.o cheb.o
SUBDIRS = 

include $(top_srcdir)/src/backend/common.mk
